import { pgTable, uuid, varchar, text, date, timestamp, jsonb, pgEnum } from 'drizzle-orm/pg-core';

export const authorWorkTypeEnum = pgEnum('author_work_type', [
  'novelist',
  'short_story_writer',
  'poet',
  'playwright',
  'screenwriter',
  'essayist',
  'biographer',
  'memoirist',
  'historian',
  'journalist',
  'science_writer',
  'self_help_writer',
  'children_writer',
  'young_adult_writer',
  'graphic_novelist',
  'fantasy_writer',
  'sci_fi_writer',
  'mystery_writer',
  'romance_writer',
  'horror_writer',
  'other',
]);

export const authors = pgTable('authors', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: varchar('name', { length: 100 }).notNull(),
  bio: text('bio'),
  birthDate: date('birth_date'),
  birthPlace: varchar('birth_place', { length: 100 }),
  nationality: varchar('nationality', { length: 50 }),
  typeOfWork: authorWorkTypeEnum('type_of_work'),
  website: varchar('website', { length: 255 }),
  profilePicture: text('profile_picture'),
  deathDate: date('death_date'),
  socialMediaLinks: jsonb('social_media_links'),
  mediaImages: jsonb('media_images'),
  mediaVideos: jsonb('media_videos'),
  funFacts: jsonb('fun_facts'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});
